function normalizeItem(raw){const o=raw&&typeof raw==="object"?raw:{};const deadline=o.deadline??o.expires_at??o.expire_at??o.expires??null;const url=o.url??o.link??o.source_url??"";const model=o.model??o.name??o.model_name??"未知模型";const type=o.type??(Array.isArray(o.tags)?o.tags[0]:null)??"其他";const title=o.title??o.name??model;const collected=o.collected_at??o.collectedAt??o.created_at??o.scraped_at??null;const expiredFlag=o.expired===true||o.is_expired===true;return{id:String(o.id??url??title??Math.random()),title:String(title),model:String(model),type:String(type),deadline:deadline?String(deadline):null,url:String(url||""),summary:String(o.summary??o.desc??o.description??""),source:String(o.source??"x"),collected_at:collected?String(collected):null,expiredFlag};}
function isExpired(item,now=Date.now()){if(item.expiredFlag)return true;if(!item.deadline)return false;const t=Date.parse(item.deadline);return Number.isNaN(t)?false:t<now;}
function sortKey(item){const c=item.collected_at?Date.parse(item.collected_at):NaN;const d=item.deadline?Date.parse(item.deadline):NaN;return!Number.isNaN(c)?c:(!Number.isNaN(d)?d:0);}
function fmtDate(iso){if(!iso)return"—";const t=Date.parse(iso);if(Number.isNaN(t))return iso;try{return new Intl.DateTimeFormat("zh-CN",{timeZone:"Asia/Shanghai",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"}).format(t)+" CST";}catch{return new Date(t).toLocaleString("zh-CN");}}
function escapeHtml(s){return String(s).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");}
const items=(Array.isArray(ITEMS)?ITEMS:[]).map(normalizeItem).sort((a,b)=>sortKey(b)-sortKey(a));
const state={model:"全部",type:"全部",onlyActive:true};
const models=["全部",...Array.from(new Set(items.map(i=>i.model))).sort()];
const types=["全部",...Array.from(new Set(items.map(i=>i.type))).sort()];
function renderChips(el,values,key){el.innerHTML=values.map(v=>{const active=state[key]===v?" active":"";return`<button type="button" class="chip${active}" data-key="${key}" data-value="${escapeHtml(v)}">${escapeHtml(v)}</button>`;}).join("");}
function filtered(){const now=Date.now();return items.filter(it=>{if(state.model!=="全部"&&it.model!==state.model)return false;if(state.type!=="全部"&&it.type!==state.type)return false;if(state.onlyActive&&isExpired(it,now))return false;return true;});}
function renderStats(){const now=Date.now();const active=items.filter(i=>!isExpired(i,now)).length;document.getElementById("stats").innerHTML=`<div class="stat"><strong>${items.length}</strong>条合计</div><div class="stat"><strong>${active}</strong>条未过期</div><div class="stat"><strong>${items.length-active}</strong>条已过期</div>`;}
function renderList(){const list=document.getElementById("list");const rows=filtered();if(!items.length){list.innerHTML=`<div class="empty"><div class="emoji">🛰️</div><h2>暂无条目</h2><p>猎手还在扫描 X 上的免费模型帖子，有新发现会自动更新到这里。</p></div>`;return;}if(!rows.length){list.innerHTML=`<div class="empty"><div class="emoji">🔍</div><h2>没有匹配的结果</h2><p>试试调整筛选条件，或取消「只看未过期」。</p></div>`;return;}const now=Date.now();list.innerHTML=rows.map(it=>{const expired=isExpired(it,now);const statusBadge=expired?`<span class="badge dead">已过期</span>`:`<span class="badge ok">进行中</span>`;const deadlineBadge=it.deadline?(expired?`<span class="badge dead">截止 ${escapeHtml(fmtDate(it.deadline))}</span>`:`<span class="badge warn">截止 ${escapeHtml(fmtDate(it.deadline))}</span>`):`<span class="badge">无限期 / 未标注</span>`;const link=it.url?`<a href="${escapeHtml(it.url)}" target="_blank" rel="noopener noreferrer">查看原帖</a>`:"";const titleHtml=it.url?`<a href="${escapeHtml(it.url)}" target="_blank" rel="noopener noreferrer">${escapeHtml(it.title)}</a>`:escapeHtml(it.title);return`<article class="card${expired?" expired":""}"><div class="card-top"><h2 class="card-title">${titleHtml}</h2><div class="badges"><span class="badge model">${escapeHtml(it.model)}</span><span class="badge type">${escapeHtml(it.type)}</span>${statusBadge}</div></div>${it.summary?`<p class="summary">${escapeHtml(it.summary)}</p>`:""}<div class="meta"><span>${deadlineBadge}</span><span>收录 ${escapeHtml(fmtDate(it.collected_at))}</span>${link?`<span>${link}</span>`:""}</div></article>`;}).join("");}
function renderAll(){renderChips(document.getElementById("modelChips"),models,"model");renderChips(document.getElementById("typeChips"),types,"type");renderStats();renderList();}
document.querySelector(".filters").addEventListener("click",e=>{const btn=e.target.closest(".chip");if(!btn)return;state[btn.dataset.key]=btn.dataset.value;renderAll();});
document.getElementById("onlyActive").addEventListener("change",e=>{state.onlyActive=e.target.checked;renderList();});
(function(){const html=document.documentElement;const saved=localStorage.getItem("fm-theme");if(saved==="light"||saved==="dark")html.classList.add("theme-"+saved);document.getElementById("themeToggle").addEventListener("click",()=>{const isDark=html.classList.contains("theme-dark")||(!html.classList.contains("theme-light")&&matchMedia("(prefers-color-scheme: dark)").matches);html.classList.remove("theme-light","theme-dark");html.classList.add(isDark?"theme-light":"theme-dark");localStorage.setItem("fm-theme",isDark?"light":"dark");});})();
renderAll();
